general:
  fee_discount: 0.95
  results_folder: "data/"
  report_ipocmp_statistics: False
  output_planning_tree: False
  include_random: True
  skip_random: True
  skip_rational: False
  number_of_rational_agents: 2
  sender_thresholds: [0.0,0.15,0.6]
  receiver_thresholds: [0.0,0.3]
  state: test

environments:
  first_task:
    n_trials: 10
    planning_depth: 10
    uct_exploration_bonus: 5.0
    rollout_rejecting_bonus: 0.5
    mcts_number_of_iterations: 25000
    discount_factor: 0.99
    endowment: 1.0
    break_down_policy: False
    active_detection_mechanism: False
    subintentional_type: softmax
    subintentional_weight: -0.95
  x_ipomdp:
    n_trials: 10
    planning_depth: 10
    uct_exploration_bonus: 5.0
    rollout_rejecting_bonus: 0.5
    mcts_number_of_iterations: 10000
    discount_factor: 0.99
    endowment: 1.0
    break_down_policy: True
    active_detection_mechanism: True
    subintentional_type: softmax
    subintentional_weight: -0.95
