general:
  fee_discount: 0.95
  results_folder: "data/agent_subject/"

environments:
  basic_task:
    name: basic_task
    uct_exploration_bonus: 5.0
    rollout_rejecting_bonus: 0.5
    planning_depth: 10
    mcts_number_of_iterations: 10000
    discount_factor: 0.95
