general:
  fee_discount: 0.95
  results_folder: "data/agent_subject/"

environments:
  env_2:
    name: env_2
    uct_exploration_bonus: 5.0
    rollout_rejecting_bonus: 0.5
    planning_depth: 10
    mcts_number_of_iterations: 10000
