general:
  fee_discount: 0.95
  results_folder: "data/"
  report_ipocmp_statistics: False
  output_planning_tree: True
  include_random: True
  skip_random: True
  skip_rational: False
  number_of_rational_agents: 2
  thresholds: [0.0,0.2,0.8]

environments:
  first_task:
    n_trials: 10
    planning_depth: 10
    uct_exploration_bonus: 5.0
    rollout_rejecting_bonus: 0.5
    mcts_number_of_iterations: 6000
    discount_factor: 0.99
    endowment: 1.0
    break_down_policy: False
    subintentional_type: softmax
    subintentional_weight: -0.95
  x_ipomdp:
    n_trials: 10
    planning_depth: 10
    uct_exploration_bonus: 5.0
    rollout_rejecting_bonus: 0.5
    mcts_number_of_iterations: 6000
    discount_factor: 0.95
    endowment: 1.0
    break_down_policy: True
    subintentional_type: softmax
    subintentional_weight: -0.95
